# frozen_string_literal: true

require_relative "test_helper"

# Cross-check MES for ordinal ballots against pabutools' method_of_equal_shares with
# Additive_Borda_Sat, on synthetic fixtures. The Ruby parser converts ordinal ballots
# to per-voter Borda scores (ballot length - rank - 1) and reuses the general MES.
# Ties are resolved identically via pabutools' lexicographic order.
#
# The reference (test/fixtures/pabutools_ordinal_reference.json) is generated by
# test/fixtures/generate_pabutools_ordinal_reference.py and is optional (tests skip
# when absent).
class PabutoolsOrdinalTest < Minitest::Test
  include TestSupport

  REFERENCE = File.join(__dir__, "fixtures", "pabutools_ordinal_reference.json")

  def setup
    skip "pabutools ordinal reference not generated" unless File.exist?(REFERENCE)
    @reference = JSON.parse(File.read(REFERENCE))
  end

  def test_ordinal_borda_scores_are_computed
    instance = Equalshares::Pabulib.parse_file(
      File.join(REPO_ROOT, "test/fixtures/pb_ordinal/synthetic_ordinal.pb")
    )
    assert_predicate instance, :cardinal?
    # A voter ranking "a,b,c" gives Borda scores 2,1,0 -> only a and b are supporters.
    refute_nil instance.scores
  end

  def test_ordinal_mes_matches_pabutools_borda
    @reference.each do |rel_path, expected|
      instance = Equalshares::Pabulib.parse_file(File.join(REPO_ROOT, rel_path))
      params = Equalshares::Params.new(accuracy: "fractions", tie_breaking: [{ lexico: expected["lexico_order"] }])

      direct = Equalshares::MesGeneral.equal_shares(instance, params)
      delegated = Equalshares::Compute.equal_shares(instance, params)

      assert_equal expected["winners"].sort, direct.winners.sort,
                   "ordinal MES winner set mismatch vs pabutools for #{rel_path}"
      assert_equal direct.winners.sort, delegated.winners.sort,
                   "Compute delegation differs from MesGeneral for #{rel_path}"
    end
  end
end
