# frozen_string_literal: true

require_relative "test_helper"

# Cross-check the maximin support rule against pabutools' maximin_support on small
# synthetic approval fixtures. The Ruby implementation computes the minimum max-load
# exactly (max-density via max-flow) rather than via an LP, so it must match pabutools.
# Ties are resolved identically via pabutools' lexicographic order.
#
# The reference (test/fixtures/pabutools_maximin_reference.json) is generated by
# test/fixtures/generate_pabutools_maximin_reference.py and is optional (tests skip
# when absent).
class PabutoolsMaximinTest < Minitest::Test
  include TestSupport

  REFERENCE = File.join(__dir__, "fixtures", "pabutools_maximin_reference.json")

  def setup
    skip "pabutools maximin reference not generated" unless File.exist?(REFERENCE)
    @reference = JSON.parse(File.read(REFERENCE))
  end

  def test_maximin_matches_pabutools
    @reference.each do |rel_path, expected|
      instance = Equalshares::Pabulib.parse_file(File.join(REPO_ROOT, rel_path))
      params = Equalshares::Params.new(tie_breaking: [{ lexico: expected["lexico_order"] }])
      result = Equalshares::Maximin.support(instance, params)
      assert_equal expected["winners"].sort, result.winners.sort,
                   "maximin winner set mismatch vs pabutools for #{rel_path}"
    end
  end
end
