# frozen_string_literal: true

require_relative "test_helper"

# Cross-check MES for cardinal ballots (scoring/cumulative) against pabutools'
# method_of_equal_shares with Additive_Cardinal_Sat, on synthetic fixtures with
# per-voter scores. Ties are resolved identically via pabutools' lexicographic order.
#
# The reference (test/fixtures/pabutools_cardinal_reference.json) is generated by
# test/fixtures/generate_pabutools_cardinal_reference.py and is optional (tests skip
# when absent).
class PabutoolsCardinalTest < Minitest::Test
  include TestSupport

  REFERENCE = File.join(__dir__, "fixtures", "pabutools_cardinal_reference.json")

  def setup
    skip "pabutools cardinal reference not generated" unless File.exist?(REFERENCE)
    @reference = JSON.parse(File.read(REFERENCE))
  end

  def test_cardinal_instances_are_detected
    instance = Equalshares::Pabulib.parse_file(
      File.join(REPO_ROOT, "test/fixtures/pb_cardinal/synthetic_scoring.pb")
    )
    assert_predicate instance, :cardinal?
    refute_nil instance.scores
  end

  def test_cardinal_mes_matches_pabutools
    @reference.each do |rel_path, expected|
      instance = Equalshares::Pabulib.parse_file(File.join(REPO_ROOT, rel_path))
      params = Equalshares::Params.new(accuracy: "fractions", tie_breaking: [{ lexico: expected["lexico_order"] }])

      # via the general rule directly, and via the public Compute API (which delegates)
      direct = Equalshares::MesGeneral.equal_shares(instance, params)
      delegated = Equalshares::Compute.equal_shares(instance, params)

      assert_equal expected["winners"].sort, direct[:winners].sort,
                   "cardinal MES winner set mismatch vs pabutools for #{rel_path}"
      assert_equal direct[:winners].sort, delegated[:winners].sort,
                   "Compute delegation differs from MesGeneral for #{rel_path}"
    end
  end
end
