# frozen_string_literal: true

require_relative "test_helper"

# Cross-check the additional voting rules (pabutools parity) on the subsampled
# fixtures, with ties resolved identically via pabutools' lexicographic project order.
#
# The reference (test/fixtures/pabutools_rules_reference.json) is generated by
# test/fixtures/generate_pabutools_rules_reference.py and is optional: absent it, the
# tests skip.
class PabutoolsRulesTest < Minitest::Test
  include TestSupport

  REFERENCE = File.join(__dir__, "fixtures", "pabutools_rules_reference.json")

  def setup
    skip "pabutools rules reference not generated" unless File.exist?(REFERENCE)
    @reference = JSON.parse(File.read(REFERENCE))
  end

  def test_sequential_phragmen_matches_pabutools
    @reference.each do |rel_path, expected|
      instance = Equalshares::Pabulib.parse_file(File.join(REPO_ROOT, rel_path))
      params = Equalshares::Params.new(accuracy: "fractions", tie_breaking: [{ lexico: expected["lexico_order"] }])
      result = Equalshares::Phragmen.sequential(instance, params)
      assert_equal expected["phragmen"].sort, result.winners.sort,
                   "phragmen winner set mismatch vs pabutools for #{rel_path}"
    end
  end

  def test_greedy_utilitarian_welfare_matches_pabutools
    @reference.each do |rel_path, expected|
      instance = Equalshares::Pabulib.parse_file(File.join(REPO_ROOT, rel_path))
      %w[cost cardinality].each do |measure|
        params = Equalshares::Params.new(
          accuracy: "fractions", satisfaction: measure,
          tie_breaking: [{ lexico: expected["lexico_order"] }]
        )
        result = Equalshares::Greedy.utilitarian_welfare(instance, params)
        assert_equal expected["greedy_#{measure}"].sort, result.winners.sort,
                     "greedy(#{measure}) winner set mismatch vs pabutools for #{rel_path}"
      end
    end
  end
end
