# frozen_string_literal: true

require_relative "test_helper"

# Independent cross-check against pabutools, the academic reference implementation
# of the Method of Equal Shares. The equalshares.net tool (and this port) implements
# MES with *cost* satisfaction and exact arithmetic; that mapping was confirmed
# empirically (the port matches pabutools' Cost_Sat, not Cardinality_Sat).
#
# The pabutools reference (test/fixtures/pabutools_reference.json) is generated by
# test/fixtures/generate_pabutools_reference.py and is optional: if it is absent
# (pabutools not installed) these tests are skipped, so the Ruby-only suite still runs.
#
# To resolve ties identically, the Ruby side is given pabutools' full lexicographic
# project order as an explicit candidate-order tie-breaking list.
class PabutoolsCrossCheckTest < Minitest::Test
  include TestSupport

  REFERENCE = File.join(__dir__, "fixtures", "pabutools_reference.json")

  def setup
    skip "pabutools reference not generated (see generate_pabutools_reference.py)" unless File.exist?(REFERENCE)
    @reference = JSON.parse(File.read(REFERENCE))
  end

  def test_pure_mes_matches_pabutools_cost_sat
    @reference.each do |rel_path, expected|
      instance = Equalshares::Pabulib.parse_file(File.join(REPO_ROOT, rel_path))
      params = Equalshares::Params.new(
        completion: "none",
        accuracy: "fractions",
        tie_breaking: [{ lexico: expected["lexico_order"] }] # pabutools-style total order
      )
      result = Equalshares::Compute.equal_shares(instance, params)

      assert_equal expected["winners"].sort, result[:winners].sort,
                   "winner set mismatch vs pabutools for #{rel_path}"
      assert_equal expected["total_cost"], result[:notes][:stats][:total_cost].round,
                   "total cost mismatch vs pabutools for #{rel_path}"
    end
  end
end
