# frozen_string_literal: true

require_relative "test_helper"

# Cross-check the generalised satisfaction measures (pabutools parity). The Ruby MES
# is checked against pabutools' Cost_Sat and Cardinality_Sat on the subsampled
# fixtures, with ties resolved identically via pabutools' lexicographic project order.
#
# The reference (test/fixtures/pabutools_satisfaction_reference.json) is generated by
# test/fixtures/generate_pabutools_satisfaction_reference.py and is optional: absent it,
# these tests skip.
class PabutoolsSatisfactionTest < Minitest::Test
  include TestSupport

  REFERENCE = File.join(__dir__, "fixtures", "pabutools_satisfaction_reference.json")
  MEASURES = %w[cost cardinality effort].freeze

  def setup
    skip "pabutools satisfaction reference not generated" unless File.exist?(REFERENCE)
    @reference = JSON.parse(File.read(REFERENCE))
  end

  def test_mes_matches_pabutools_per_satisfaction
    @reference.each do |rel_path, expected|
      instance = Equalshares::Pabulib.parse_file(File.join(REPO_ROOT, rel_path))
      MEASURES.each do |measure|
        params = Equalshares::Params.new(
          completion: "none",
          accuracy: "fractions",
          satisfaction: measure,
          tie_breaking: [{ lexico: expected["lexico_order"] }]
        )
        result = Equalshares::Compute.equal_shares(instance, params)
        assert_equal expected[measure].sort, result.winners.sort,
                     "#{measure} winner set mismatch vs pabutools for #{rel_path}"
      end
    end
  end
end
